CREATE TABLE CR_TEMPLATE_RELATION
(	ID NUMBER NOT NULL ENABLE,
     TEMPLATE_IDS VARCHAR2(600 )  NOT NULL ENABLE,
     GROUP_ID NUMBER NOT NULL ENABLE,
     IS_ZIPPED VARCHAR2(1 )  NOT NULL ENABLE,
     VERSION VARCHAR2(100 ) ,
     ATTRIBUTE1 VARCHAR2(150 ) ,
     ATTRIBUTE2 VARCHAR2(150 ) ,
     ATTRIBUTE3 VARCHAR2(150 ) ,
     ATTRIBUTE4 VARCHAR2(150 ) ,
     ATTRIBUTE5 VARCHAR2(150 ) ,
     LAST_UPDATED_BY VARCHAR2(50 ) ,
     LAST_UPDATE_DATE DATE,
     CREATION_DATE DATE,
     CREATED_BY VARCHAR2(50 )
)
$#$

CREATE TABLE "CR_CREATE_BANK_BRANCH_ERRORS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"BANK_NAME" VARCHAR2(300) ,
	"BANK_NUMBER" VARCHAR2(300),
	"BRANCH_NAME" VARCHAR2(300),
	"BRANCH_NUMBER" VARCHAR2(300),
	"EFT_SWIFT_CODE" VARCHAR2(300),
	"CR_BATCH_NAME" VARCHAR2(300),
	"ERROR_TYPE" VARCHAR2(200),
	"ERROR_MESSAGE" VARCHAR2(2000),
	"CREATION_DATE" DATE,
	"CREATED_BY" VARCHAR2(200)
   )
$#$
  CREATE TABLE "CR_SUPPLIER_TAX_PROFILE_ERRORS"
   (	"ID"NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"PARTY_TAX_PROFILE_ID" VARCHAR2(100) NOT NULL ENABLE,
	"CR_BATCH_NAME" VARCHAR2(200),
	"STATUS_CODE" VARCHAR2(200),
	"ERROR_MESSAGE" VARCHAR2(3000),
	"CREATED_DATE" DATE,
	"CREATED_BY" VARCHAR2(200)
	)
$#$
CREATE TABLE "CR_PROJ_DFF_ERROR"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"PROJECT_ID" VARCHAR2(250),
	"PARENT_PROJECT_ID" VARCHAR2(250),
	"PARENT_PROJECT_NUMBER" VARCHAR2(250),
	"CR_BATCH_NAME" VARCHAR2(200),
	"ERROR_MESSAGE" VARCHAR2(2000),
	"CREATION_DATE" DATE,
	"CREATED_BY" VARCHAR2(200)
   )
 $#$
   CREATE TABLE "CR_VALIDATE_CVR_CCID"
   (
    "CLOUD_STAGING_TABLE_NAME" VARCHAR2(240),
	"CR_BATCH_NAME" VARCHAR2(240),
	"CCID" VARCHAR2(400),
	"ERROR_MESSAGE" VARCHAR2(2000),
	"ERROR_CODE" VARCHAR2(240),
	"STATUS" VARCHAR2(240),
	"ATTRIBUTE1" VARCHAR2(420),
	"ATTRIBUTE2" VARCHAR2(420) ,
	"ATTRIBUTE3" VARCHAR2(420),
	"ATTRIBUTE4" VARCHAR2(420),
	"ATTRIBUTE5" VARCHAR2(420) ,
	"ATTRIBUTE6" NUMBER,
	"ATTRIBUTE7" NUMBER,
	"ATTRIBUTE8" NUMBER,
	"ATTRIBUTE9" NUMBER,
	"ATTRIBUTE10" NUMBER,
	"ATTRIBUTE11" DATE,
	"ATTRIBUTE12" DATE,
	"CREATION_DATE" DATE,
	"CREATED_BY" VARCHAR2(240),
	"LAST_UPDATE_DATE" DATE,
	"LAST_UPDATED_BY" VARCHAR2(240),
	"REQUEST_ID" NUMBER
   )
 $#$
 DROP TABLE CR_SOURCE_LOAD_FAIL_RECORDS
 $#$
 DROP TABLE CR_SRC_LOADDATA_FAIL_RECORDS

 $#$
 CREATE TABLE CR_SRC_LOADDATA_FAIL_RECORDS (
     RECORD_ID               NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
     SRC_TEMPLATE_ID         NUMBER,
     FILE_NAME               VARCHAR2(300),
     LOG_FILE_BLOB           CLOB,
     CR_BATCH_NAME           VARCHAR2(240),
     FAILED_CLOB             CLOB,
     SUCCESS_COUNT           NUMBER,
     FAILED_COUNT            NUMBER,
     ATTRIBUTE1              VARCHAR2(150),
     ATTRIBUTE2              VARCHAR2(150),
     ATTRIBUTE3              VARCHAR2(150),
     ATTRIBUTE4              VARCHAR2(150),
     ATTRIBUTE5              VARCHAR2(150),
     CREATION_DATE           DATE NOT NULL,
     CREATED_BY              VARCHAR2(200) NOT NULL,
     LAST_UPDATE_DATE        DATE,
     LAST_UPDATED_BY         VARCHAR2(200)
 )
  $#$
