
DECLARE
    

l_copy_log_count NUMBER ;

BEGIN
    -- Check if the table exists
    SELECT
        COUNT(*)
    INTO l_copy_log_count
    FROM
        all_tables
    WHERE
        table_name = 'CR_COPY_LOG';

    IF l_copy_log_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CR_COPY_LOG 
   (	COPY_ID NUMBER, 
	SOURCE_POD VARCHAR2(240 BYTE) , 
	DESTINATION_POD VARCHAR2(240 BYTE) , 
	PROJECT_NAME VARCHAR2(240 BYTE), 
	LOG_CLOB CLOB , 
	DYNAMIC_SQL CLOB , 
	STATUS VARCHAR2(240),
	ERROR_MSG VARCHAR2(4200),
	ATTRIBUTE1 VARCHAR2(240 BYTE) , 
	ATTRIBUTE2 VARCHAR2(240 BYTE) , 
	ATTRIBUTE3 VARCHAR2(240 BYTE) , 
	ATTRIBUTE4 VARCHAR2(240 BYTE) , 
	CREATED_BY VARCHAR2(240 BYTE) , 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(240 BYTE) , 
	LAST_UPDATED_DATE DATE, 
	 PRIMARY KEY (COPY_ID))';
    END IF;
END;
$#$
