
DECLARE
    l_check NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_check
    FROM
        all_tables
    WHERE
        table_name = 'CR_OBJECTS';

    IF l_check = 0 THEN
        EXECUTE IMMEDIATE Q'[CREATE TABLE cr_objects (
    object_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_name VARCHAR2(150),
    object_code VARCHAR2(150),
    user_object_name VARCHAR2(150),
    module_code VARCHAR2(150),
    parent_object_id NUMBER,
    fbdi_sheet VARCHAR2(150),
    hdl_sheet VARCHAR2(150),
    loader_endpoint VARCHAR2(350),
    re_con_query CLOB,
    sequence_in_parent NUMBER,
    interface_table_name VARCHAR2(150),
    rejection_table_name VARCHAR2(150),
    ctl_file_name VARCHAR2(150),
    xlsm_file_name VARCHAR2(150),
    immediate_parent VARCHAR2(150),
    batch_size NUMBER,
    base_tables VARCHAR2(150),
     creation_date DATE NOT NULL,
    created_by VARCHAR2(150) NOT NULL,
    last_update_date DATE NOT NULL,
    last_update_by VARCHAR2(150) NOT NULL,
	ATTRIBUTE1 VARCHAR2(240),
    ATTRIBUTE2 VARCHAR2(240),
    ATTRIBUTE3 VARCHAR2(240),
    ATTRIBUTE4 VARCHAR2(240),
    ATTRIBUTE5 VARCHAR2(240),
    ATTRIBUTE6 VARCHAR2(240),
    ATTRIBUTE7 VARCHAR2(240),
    ATTRIBUTE8 VARCHAR2(240),
    ATTRIBUTE9 VARCHAR2(240),
    ATTRIBUTE10 VARCHAR2(240),
    ATTRIBUTE11 VARCHAR2(240),
    ATTRIBUTE12 VARCHAR2(240),
    ATTRIBUTE13 VARCHAR2(240),
    ATTRIBUTE14 VARCHAR2(240),
    ATTRIBUTE15 VARCHAR2(240),
   CONVERSION_TYPE VARCHAR2(255)
)]';
    END IF;
    l_check := 0;
    SELECT
        COUNT(1)
    INTO l_check
    FROM
        all_tables
    WHERE
        table_name = 'CR_OBJECT_INFORMATION';

    IF l_check = 0 THEN
        EXECUTE IMMEDIATE Q'[CREATE TABLE cr_object_information (
    obj_info_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id NUMBER NOT NULL,
    info_type VARCHAR2(250),
    info_value CLOB,
    info_description VARCHAR2(400),
    additional_information1 CLOB,
    additional_information2 CLOB,
    additional_information3 CLOB,
    additional_information4 CLOB,
    additional_information5 CLOB,
    creation_date DATE NOT NULL,
    created_by VARCHAR2(150) NOT NULL,
    last_update_date DATE NOT NULL,
    last_update_by VARCHAR2(150) NOT NULL,
	 ATTRIBUTE1 VARCHAR2(240),
    ATTRIBUTE2 VARCHAR2(240),
    ATTRIBUTE3 VARCHAR2(240),
    ATTRIBUTE4 VARCHAR2(240),
    ATTRIBUTE5 VARCHAR2(240),
    ATTRIBUTE6 VARCHAR2(240),
    ATTRIBUTE7 VARCHAR2(240),
    ATTRIBUTE8 VARCHAR2(240),
    ATTRIBUTE9 VARCHAR2(240),
    ATTRIBUTE10 VARCHAR2(240),
    ATTRIBUTE11 VARCHAR2(240),
    ATTRIBUTE12 VARCHAR2(240),
    ATTRIBUTE13 VARCHAR2(240),
    ATTRIBUTE14 VARCHAR2(240),
    ATTRIBUTE15 VARCHAR2(240),
    CONVERSION_TYPE VARCHAR2(255)
)]';
    END IF;
END;
$#$
