CREATE TABLE CR_PROJECTS (
    PROJECT_ID NUMBER NOT NULL ENABLE,
    PROJECT_NAME VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    PROJECT_CODE VARCHAR2(250) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(100 BYTE) ,
    PROJECT_MANAGER VARCHAR2(50 BYTE),
    PROGRAM_NUMBER VARCHAR2(50 BYTE),
    CLIENT_MANAGER VARCHAR2(50 BYTE),
    KPI_AGG_LEVEL VARCHAR2(50 BYTE),
    START_DATE DATE NOT NULL ENABLE,
    END_DATE DATE,
    PROJECT_STATUS VARCHAR2(50 BYTE),
    ACCESS_LEVEL VARCHAR2(50 BYTE),
    CLIENT_PROJECT_NUMBER VARCHAR2(50 BYTE) ,
    ATTRIBUTE1 VARCHAR2(150 BYTE) ,
    ATTRIBUTE2 VARCHAR2(150 BYTE) ,
    ATTRIBUTE3 VARCHAR2(150 BYTE) ,
    ATTRIBUTE4 VARCHAR2(150 BYTE) ,
    ATTRIBUTE5 VARCHAR2(150 BYTE) ,
    LAST_UPDATED_BY VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    LAST_UPDATE_DATE DATE NOT NULL ENABLE,
    CREATION_DATE DATE,
    CREATED_BY VARCHAR2(50 BYTE)
)
$#$

CREATE TABLE CR_PROJECT_OBJECTS (
    project_obj_link_id number NOT NULL,
    project_id number NOT NULL,
    project_code VARCHAR2(250) NOT NULL,
    module_name VARCHAR2(150) NOT NULL,
    object_id number NOT NULL,
    OBJECT_NAME VARCHAR2(150 BYTE),
    object_code varchar2(150) NOT NULL,
    parent_object_code varchar2(150) ,
    creation_date date NULL,
    created_by varchar2(150) NULL,
    last_update_date date NULL,
    last_update_by varchar2(150) NULL
)
$#$

CREATE TABLE CR_PROJ_ACTIVITIES (
    TASK_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    PROJECT_ID NUMBER NOT NULL ENABLE,
    SEQ NUMBER NOT NULL ENABLE,
    TASK_NUM VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    TASK_NAME VARCHAR2(100 BYTE)  NOT NULL ENABLE,
    OBJECT_ID NUMBER NOT NULL ENABLE,
    TASK_TYPE VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    PRE_REQ_TASK VARCHAR2(50 BYTE) ,
    START_DATE DATE,
    END_DATE DATE,
    WEIGHTAGE NUMBER,
    COMPLETE_PERCENTAGE NUMBER,
    LEGACY_RESOURCE_ID NUMBER,
    TASK_STATUS VARCHAR2(50 BYTE) ,
    DESTINATION_RESOURCE_ID NUMBER,
    TASK_OWNER_ID NUMBER,
    COMPLETION_FLAG VARCHAR2(50 BYTE) ,
    CLOUD_RESOURCE_ID NUMBER,
    INTEGRATOR_RESOURCE_ID NUMBER,
    CLIENT_RESOURCE_ID NUMBER,
    ATTRIBUTE1 VARCHAR2(150 BYTE) ,
    ATTRIBUTE2 VARCHAR2(150 BYTE) ,
    ATTRIBUTE3 VARCHAR2(150 BYTE) ,
    ATTRIBUTE4 VARCHAR2(150 BYTE) ,
    ATTRIBUTE5 VARCHAR2(150 BYTE) ,
    LAST_UPDATED_BY VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    LAST_UPDATE_DATE DATE NOT NULL ENABLE,
    CREATION_DATE DATE,
    CREATED_BY VARCHAR2(50 BYTE)
)
$#$

