CREATE TABLE CR_FILE_DETAILS (
    FILE_ID            NUMBER   GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) ,
    CLD_FILE_ID        NUMBER,
    FILE_TYPE          VARCHAR2(50),
    FILE_NAME          VARCHAR2(200),
    FILE_CONTENT       CLOB,
    CREATION_DATE      DATE NOT NULL,
    CREATED_BY         VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE   DATE,
    LAST_UPDATED_BY    VARCHAR2(200)
)
$#$
 
CREATE TABLE CR_LOOKUP_SETS (
    LOOKUP_SET_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LOOKUP_SET_NAME VARCHAR2(50 BYTE) , 
    LOOKUP_SET_CODE VARCHAR2(50),
    DESCRIPTION VARCHAR2(100 BYTE) , 
    RELATED_TO VARCHAR2(50 BYTE) , 
    LOOKUP_FLAG VARCHAR2(1 BYTE) , 
    ATTRIBUTE1 VARCHAR2(150 BYTE) , 
    ATTRIBUTE2 VARCHAR2(150 BYTE) , 
    ATTRIBUTE3 VARCHAR2(150 BYTE) , 
    ATTRIBUTE4 VARCHAR2(150 BYTE) , 
    ATTRIBUTE5 VARCHAR2(150 BYTE) , 
    LAST_UPDATED_BY VARCHAR2(50 BYTE), 
    LAST_UPDATE_DATE DATE, 
    CREATION_DATE DATE, 
    CREATED_BY VARCHAR2(50 BYTE) 
)
$#$

CREATE TABLE CR_LOOKUP_VALUES (
    LOOKUP_VALUE_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    LOOKUP_VALUE VARCHAR2(150 BYTE), 
    LOOKUP_SET_ID NUMBER NOT NULL ENABLE, 
    ACTUAL_VALUE VARCHAR2(50 BYTE) ,
    ATTRIBUTE1 VARCHAR2(150 BYTE) , 
    ATTRIBUTE2 VARCHAR2(150 BYTE) , 
    ATTRIBUTE3 VARCHAR2(150 BYTE) , 
    ATTRIBUTE4 VARCHAR2(150 BYTE) , 
    ATTRIBUTE5 VARCHAR2(150 BYTE) , 
    ENABLED_FLAG VARCHAR2(1 BYTE) , 
    LAST_UPDATED_BY VARCHAR2(50 BYTE), 
    LAST_UPDATE_DATE DATE, 
    CREATION_DATE DATE, 
    CREATED_BY VARCHAR2(50 BYTE) 
)
$#$

CREATE TABLE CR_FORMULA_SETS (
    FORMULA_SET_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FORMULA_SET_NAME VARCHAR2(150) , 
    FORMULA_SET_CODE VARCHAR2(150),
    DESCRIPTION VARCHAR2(250) ,
    FORMULA_TYPE VARCHAR2(50 BYTE), 
    FORMULA_TEXT CLOB,
    COUNT_OF_PARAMS NUMBER,
    ATTRIBUTE1 VARCHAR2(150 BYTE) , 
    ATTRIBUTE2 VARCHAR2(150 BYTE) , 
    ATTRIBUTE3 VARCHAR2(150 BYTE) , 
    ATTRIBUTE4 VARCHAR2(150 BYTE) , 
    ATTRIBUTE5 VARCHAR2(150 BYTE) , 
    LAST_UPDATED_BY VARCHAR2(150), 
    LAST_UPDATE_DATE DATE, 
    CREATION_DATE DATE, 
    CREATED_BY VARCHAR2(150)
)
$#$

CREATE TABLE CR_MAPPING_CLOB (
    TEMPLATE_ID               NUMBER        NOT NULL,
    DYNAMIC_QUERY             CLOB,
    ALTERED                   VARCHAR2(50),
    ATTRIBUTE1                VARCHAR2(150),
    ATTRIBUTE2                VARCHAR2(150),
    ATTRIBUTE3                VARCHAR2(150),
    ATTRIBUTE4                VARCHAR2(150),
    ATTRIBUTE5                VARCHAR2(150),
    CREATION_DATE             DATE ,
    CREATED_BY                VARCHAR2(200),
    LAST_UPDATE_DATE          DATE,
    LAST_UPDATED_BY           VARCHAR2(200)
)
$#$

CREATE TABLE CR_MAPPING_SETS (
    MAP_SET_ID NUMBER GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1),
    MAP_SET_NAME VARCHAR2(50 BYTE) UNIQUE, 
    MAP_SET_CODE VARCHAR2(100 BYTE)  NOT NULL ENABLE UNIQUE, 
    MAP_SET_TYPE VARCHAR2(50 BYTE)  NOT NULL ENABLE, 
    VALIADTION_TYPE VARCHAR2(50 BYTE) , 
    LOOKUP_SET_ID NUMBER, 
    SQL_QUERY CLOB , 
    ATTRIBUTE1 VARCHAR2(150 BYTE) , 
    ATTRIBUTE2 VARCHAR2(150 BYTE) , 
    ATTRIBUTE3 VARCHAR2(150 BYTE) , 
    ATTRIBUTE4 VARCHAR2(150 BYTE) , 
    ATTRIBUTE5 VARCHAR2(150 BYTE) , 
    LAST_UPDATED_BY VARCHAR2(50 BYTE) , 
    LAST_UPDATE_DATE DATE, 
    CREATION_DATE DATE, 
    CREATED_BY VARCHAR2(50 BYTE),
    CONSTRAINT CR_MAPPING_SETS_PK PRIMARY KEY (MAP_SET_NAME, MAP_SET_CODE)
)
$#$

CREATE TABLE CR_MAPPING_VALUES (
    MAP_LINE_ID NUMBER GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1),
    MAP_SET_ID NUMBER NOT NULL ENABLE, 
    SOURCE_FIELD1 VARCHAR2(500 BYTE) , 
    SOURCE_FIELD2 VARCHAR2(500 BYTE) , 
    SOURCE_FIELD3 VARCHAR2(500 BYTE) , 
    TARGET_VALUE VARCHAR2(250 BYTE) , 
    ENABLED_FLAG VARCHAR2(1 BYTE) , 
    ATTRIBUTE1 VARCHAR2(150 BYTE) , 
    ATTRIBUTE2 VARCHAR2(150 BYTE) , 
    ATTRIBUTE3 VARCHAR2(150 BYTE) , 
    ATTRIBUTE4 VARCHAR2(150 BYTE) , 
    ATTRIBUTE5 VARCHAR2(150 BYTE) , 
    LAST_UPDATED_BY VARCHAR2(50 BYTE) , 
    LAST_UPDATE_DATE DATE, 
    CREATION_DATE DATE, 
    CREATED_BY VARCHAR2(50 BYTE) 
)
$#$

CREATE TABLE CR_SOURCE_TABLES (
    TABLE_ID                      NUMBER(15)   NOT NULL,
    TABLE_NAME                    VARCHAR2(100)  NOT NULL UNIQUE,
    USER_TABLE_NAME               VARCHAR2(80)   NOT NULL,
    DESCRIPTION                   VARCHAR2(240) ,
    OBJECT_ID                     NUMBER,
    APPLICATION_ID                NUMBER(15)  NOT NULL ,
    AUTO_SIZE                     VARCHAR2(1)  NOT NULL,
    TABLE_TYPE                    VARCHAR2(1) NOT NULL ,
    INITIAL_EXTENT                NUMBER(15)  NOT NULL ,
    NEXT_EXTENT                   NUMBER(15)  NOT NULL,
    MIN_EXTENTS                   NUMBER(15)  NOT NULL ,
    MAX_EXTENTS                   NUMBER(15)  NOT NULL ,
    PCT_INCREASE                  NUMBER(15)  NOT NULL ,
    INI_TRANS                     NUMBER(15)  NOT NULL ,
    MAX_TRANS                     NUMBER(15)  NOT NULL ,
    PCT_FREE                      NUMBER(15)  NOT NULL ,
    PCT_USED                      NUMBER(15)  NOT NULL ,
    HOSTED_SUPPORT_STYLE          VARCHAR2(30),
    IREP_COMMENTS                 VARCHAR2(4000),
    IREP_ANNOTATIONS              VARCHAR2(4000),
    ATTRIBUTE1                    VARCHAR2(150),
    ATTRIBUTE2                    VARCHAR2(150),
    ATTRIBUTE3                    VARCHAR2(150),
    ATTRIBUTE4                    VARCHAR2(150),
    ATTRIBUTE5                    VARCHAR2(150),
    CREATION_DATE                 DATE NOT NULL,
    CREATED_BY                    VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE              DATE,
    LAST_UPDATED_BY               VARCHAR2(200)
)
$#$

CREATE TABLE CR_SOURCE_COLUMNS (
    TABLE_ID                         NUMBER(15)       NOT NULL,
    COLUMN_ID                        NUMBER(15)       NOT NULL,
    COLUMN_NAME                      VARCHAR2(240)    NOT NULL,
    USER_COLUMN_NAME                 VARCHAR2(240)    NOT NULL,
    DESCRIPTION                      VARCHAR2(240),
    APPLICATION_ID                   NUMBER(15)       NOT NULL,
    COLUMN_SEQUENCE                  NUMBER(15)       NOT NULL,
    COLUMN_TYPE                      VARCHAR2(1)      NOT NULL,
    WIDTH                            NUMBER(15),
    NULL_ALLOWED_FLAG                VARCHAR2(1)      NOT NULL,
    TRANSLATE_FLAG                   VARCHAR2(1)      NOT NULL,
    FLEXFIELD_USAGE_CODE             VARCHAR2(1)      NOT NULL,
    FLEXFIELD_APPLICATION_ID         NUMBER(10),
    FLEXFIELD_NAME                   VARCHAR2(30),
    FLEX_VALUE_SET_APPLICATION_ID    NUMBER(10),
    FLEX_VALUE_SET_ID                NUMBER(10),
    DEFAULT_VALUE                    VARCHAR2(2000),
    PRECISION                        NUMBER(15),
    SCALE                            NUMBER(15),
    IREP_COMMENTS                    VARCHAR2(4000),
    ATTRIBUTE1                       VARCHAR2(150),
    ATTRIBUTE2                       VARCHAR2(150),
    ATTRIBUTE3                       VARCHAR2(150),
    ATTRIBUTE4                       VARCHAR2(150),
    ATTRIBUTE5                       VARCHAR2(150),
    CREATION_DATE                    DATE NOT NULL,
    CREATED_BY                       VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE                 DATE,
    LAST_UPDATED_BY                  VARCHAR2(200),
    CONSTRAINT SRC_COL_UNIQUE UNIQUE (TABLE_ID, COLUMN_NAME)
)
$#$

CREATE TABLE CR_SRC_TEMPLATE_HDRS (
    SRC_TEMPLATE_ID        NUMBER    GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    SRC_TEMPLATE_NAME      VARCHAR2(50 BYTE) UNIQUE,
    SRC_TEMPLATE_CODE      VARCHAR2(50) UNIQUE,
    PROJECT_ID             NUMBER,
    PARENT_OBJECT_ID       NUMBER,
    OBJECT_ID              NUMBER,
    METADATA_TABLE_ID      NUMBER,
    STAGING_TABLE_NAME     VARCHAR2(150 BYTE),
    NORMALIZE_DATA_FLAG    VARCHAR2(10),
    VIEW_NAME              VARCHAR2(150 BYTE),
    ATTRIBUTE1             VARCHAR2(150 BYTE),
    ATTRIBUTE2             VARCHAR2(150 BYTE),
    ATTRIBUTE3             VARCHAR2(150 BYTE),
    ATTRIBUTE4             VARCHAR2(150 BYTE),
    ATTRIBUTE5             VARCHAR2(150 BYTE),
    CREATION_DATE          DATE NOT NULL,
    CREATED_BY             VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE       DATE,
    LAST_UPDATED_BY        VARCHAR2(200),
    CONSTRAINT SRC_TEMP_HDR_UNIQUE UNIQUE (PROJECT_ID, OBJECT_ID)
)
$#$

CREATE TABLE CR_SRC_TEMPLATE_COLS (
    COLUMN_ID                  NUMBER       GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1 ),
    SRC_TEMPLATE_ID            NUMBER,
    COLUMN_NAME                VARCHAR2(240),
    COLUMN_TYPE                VARCHAR2(50),
    WIDTH                      NUMBER,
    DISPLAY_SEQ                NUMBER,
    SELECTED                   VARCHAR2(1),
    UNIQUE_TRANS_REF           VARCHAR2(1),
    ATTRIBUTE1                 VARCHAR2(150),
    ATTRIBUTE2                 VARCHAR2(150),
    ATTRIBUTE3                 VARCHAR2(150),
    ATTRIBUTE4                 VARCHAR2(150),
    ATTRIBUTE5                 VARCHAR2(150),
    CREATION_DATE              DATE NOT NULL,
    CREATED_BY                 VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE           DATE,
    LAST_UPDATED_BY            VARCHAR2(200),
    CONSTRAINT SRC_TEMP_COL_UNIQUE UNIQUE (SRC_TEMPLATE_ID, COLUMN_NAME)
)
$#$

CREATE TABLE CR_SRC_LOADDATA_FAIL_RECORDS (
    RECORD_ID               NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    SRC_TEMPLATE_ID         NUMBER,
    FILE_NAME               VARCHAR2(300),
    LOG_FILE_BLOB           BLOB,
    CR_BATCH_NAME           VARCHAR2(240),
    FAILED_CLOB             CLOB,
    SUCCESS_COUNT           NUMBER,
    FAILED_COUNT            NUMBER,
    ATTRIBUTE1              VARCHAR2(150),
    ATTRIBUTE2              VARCHAR2(150),
    ATTRIBUTE3              VARCHAR2(150),
    ATTRIBUTE4              VARCHAR2(150),
    ATTRIBUTE5              VARCHAR2(150),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE        DATE,
    LAST_UPDATED_BY         VARCHAR2(200)
)
$#$

CREATE TABLE CR_CLOUD_TABLES (
    TABLE_ID                        NUMBER          NOT NULL,
    TABLE_NAME                      VARCHAR2(1000)  NOT NULL UNIQUE,
    PHYSICAL_TABLE_NAME             VARCHAR2(1000)  NOT NULL,
    USER_TABLE_NAME                 VARCHAR2(1000)  NOT NULL,
    DESCRIPTION                     VARCHAR2(1000),
    OBJECT_ID                       NUMBER,
    PARENT_OBJECT_ID                VARCHAR2(100),
    APPLICATION_SHORT_NAME          VARCHAR2(1000)  NOT NULL,
    TABLE_TYPE                      VARCHAR2(1000),
    HOSTED_SUPPORT_STYLE            VARCHAR2(1000),
    LOGICAL                         VARCHAR2(1000),
    MLS_SUPPORT_MODEL               VARCHAR2(1000),
    STATUS                          VARCHAR2(1000),
    DEPLOY_TO                       VARCHAR2(1000),
    EXTENSION_OF_TABLE              VARCHAR2(1000),
    SHORT_NAME                      VARCHAR2(1000),
    SHARED_OBJECT                   VARCHAR2(1000),
    CONFLICT_RESOLUTION             VARCHAR2(1000),
    TABLESPACE_TYPE                 VARCHAR2(1000),
    SELECT_ALLOWED                  VARCHAR2(1000),
    INSERT_ALLOWED                  VARCHAR2(1000),
    UPDATE_ALLOWED                  VARCHAR2(1000),
    DELETE_ALLOWED                  VARCHAR2(1000),
    TRUNCATE_ALLOWED                VARCHAR2(1000),
    MAINTAIN_PARTITION              VARCHAR2(1000),
    EXCHANGE_PARTITION              VARCHAR2(1000),
    MAINTAIN_INDEX                  VARCHAR2(1000),
    FLASHBACK_ALLOWED               VARCHAR2(1000),
    ENABLE_AUDIT                    VARCHAR2(1000),
    ORA_EDITION_CONTEXT             VARCHAR2(1000),
    ATTRIBUTE1                      VARCHAR2(150),
    ATTRIBUTE2                      VARCHAR2(150),
    ATTRIBUTE3                      VARCHAR2(150),
    ATTRIBUTE4                      VARCHAR2(150),
    ATTRIBUTE5                      VARCHAR2(150),
    CREATION_DATE                   DATE NOT NULL,
    CREATED_BY                      VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE                DATE,
    LAST_UPDATED_BY                 VARCHAR2(200)
)
$#$

CREATE TABLE CR_CLOUD_COLUMNS (
    COLUMN_ID                            NUMBER           NOT NULL,
    COLUMN_NAME                          VARCHAR2(1000)   NOT NULL,
    PHYSICAL_COLUMN_NAME                 VARCHAR2(1000)   NOT NULL,
    USER_COLUMN_NAME                     VARCHAR2(1000)   NOT NULL,
    DESCRIPTION                          VARCHAR2(1000),
    TABLE_ID                             VARCHAR2(1000)   NOT NULL,
    OBJECT_ID                            NUMBER,
    STATUS                               VARCHAR2(1000),
    SHORT_NAME                           VARCHAR2(1000),
    ORA_EDITION_CONTEXT                  VARCHAR2(1000),
    COLUMN_SEQUENCE                      VARCHAR2(1000),
    COLUMN_TYPE                          VARCHAR2(1000),
    WIDTH                                VARCHAR2(1000),
    NULL_ALLOWED_FLAG                    VARCHAR2(1000),
    TRANSLATE_FLAG                       VARCHAR2(1000),
    PRECISION                            VARCHAR2(1000),
    SCALE                                VARCHAR2(1000),
    DOMAIN_CODE                          VARCHAR2(1000),
    DENORM_PATH                          VARCHAR2(1000),
    ROUTING_MODE                         VARCHAR2(1000),
    CLOUD_VERSION                        VARCHAR2(1000),
    ELIGIBLE_TO_BE_SECURED               VARCHAR2(1000),
    SECURITY_CLASSIFICATION              VARCHAR2(1000),
    SEC_CLASSIFICATION_OVERRIDE          VARCHAR2(1000),
    ATTRIBUTE1                           VARCHAR2(150) ,
    ATTRIBUTE2                           VARCHAR2(150),
    ATTRIBUTE3                           VARCHAR2(150),
    ATTRIBUTE4                           VARCHAR2(150),
    ATTRIBUTE5                           VARCHAR2(150),
    CREATION_DATE                        DATE NOT NULL,
    CREATED_BY                           VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE                     DATE,
    LAST_UPDATED_BY                      VARCHAR2(200),
    CONSTRAINT CLD_COL_UNIQUE UNIQUE (TABLE_ID, COLUMN_NAME)
)
$#$

CREATE TABLE CR_CLD_TEMPLATE_HDRS (
    CLD_TEMPLATE_ID            NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    CLD_TEMPLATE_NAME          VARCHAR2(100 BYTE)  UNIQUE,
    CLD_TEMPLATE_CODE          VARCHAR2(50)      NOT NULL UNIQUE,
    CLOUD_VERSION              VARCHAR2(50)      NOT NULL,
    PROJECT_ID                 NUMBER NOT NULL,
    PARENT_OBJECT_ID           NUMBER NOT NULL,
    OBJECT_ID                  NUMBER NOT NULL,
    METADATA_TABLE_ID          NUMBER,
    SRC_TEMPLATE_ID            NUMBER,
    STAGING_TABLE_NAME         VARCHAR2(100 BYTE),
    VIEW_NAME                  VARCHAR2(50 BYTE),
    PRIMARY_TEMPLATE_FLAG      VARCHAR2(10),
    ATTRIBUTE1                 VARCHAR2(150 BYTE),
    ATTRIBUTE2                 VARCHAR2(150 BYTE),
    ATTRIBUTE3                 VARCHAR2(150 BYTE),
    ATTRIBUTE4                 VARCHAR2(150 BYTE),
    ATTRIBUTE5                 VARCHAR2(150 BYTE),
    CREATION_DATE              DATE NOT NULL,
    CREATED_BY                 VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE           DATE,
    LAST_UPDATED_BY            VARCHAR2(200)  ,
	CONSTRAINT CLD_TEMP_HDR_UNIQUE UNIQUE (PROJECT_ID, OBJECT_ID)
)
$#$

CREATE TABLE CR_CLD_TEMPLATE_COLS  (
    COLUMN_ID               NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    COLUMN_NAME             VARCHAR2(50 BYTE),
    CLD_TEMPLATE_ID         NUMBER,
    DESCRIPTION             VARCHAR2(1000 BYTE),
    COLUMN_TYPE             VARCHAR2(50 BYTE),
    WIDTH                   NUMBER,
    DISPLAY_SEQ             NUMBER,
    NULL_ALLOWED_FLAG       VARCHAR2(1 BYTE),
    UNIQUE_TRANS_REF        VARCHAR2(1),
    SELECTED                VARCHAR2(1 BYTE),
    SOURCE_COLUMN_ID        NUMBER,
    MAPPING_TYPE            VARCHAR2(50 BYTE),
    MAPPING_SET_ID          NUMBER,
    MAPPING_VALUE1          VARCHAR2(100),
    MAPPING_VALUE2          VARCHAR2(100),
    MAPPING_VALUE3          VARCHAR2(100),
    MAPPING_VALUE4          VARCHAR2(100),
    MAPPING_VALUE5          VARCHAR2(100),
    ATTRIBUTE1              VARCHAR2(150 BYTE),
    ATTRIBUTE2              VARCHAR2(150 BYTE),
    ATTRIBUTE3              VARCHAR2(150 BYTE),
    ATTRIBUTE4              VARCHAR2(150 BYTE),
    ATTRIBUTE5              VARCHAR2(150 BYTE),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE        DATE,
    LAST_UPDATED_BY         VARCHAR2(200),
    CONSTRAINT CLD_TEMP_COL_UNIQUE UNIQUE (CLD_TEMPLATE_ID, COLUMN_NAME)
)
$#$

CREATE TABLE cr_user_hooks (
    hook_id          NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    hook_type        VARCHAR2(150),
    hook_name        VARCHAR2(250),
    hook_code        VARCHAR2(150),
    description      VARCHAR2(400),
    hook_text        CLOB,
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    creation_date    DATE,
    created_by       VARCHAR2(200),
    last_update_date DATE,
    last_updated_by  VARCHAR2(200)
)
$#$

CREATE TABLE cr_hook_usages (
    hook_usage_id    NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    hook_id          NUMBER,
    template_id      NUMBER,
    usage_type       VARCHAR2(150),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    creation_date    DATE,
    created_by       VARCHAR2(200),
    last_update_date DATE,
    last_updated_by  VARCHAR2(200)
)
$#$

CREATE TABLE CR_FBDI_TEMPLATE_HDRS (
    FBDI_TEMPLATE_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1,
    FBDI_TEMPLATE_NAME VARCHAR2(50 ),
    PROJECT_ID NUMBER NOT NULL ENABLE,
    PARENT_OBJECT_ID NUMBER NOT NULL ENABLE,
    OBJECT_ID NUMBER NOT NULL ENABLE,
    CLOUD_VERSION VARCHAR2(20),
    SHEET_NAME VARCHAR2(50),
    API VARCHAR2(200),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    CREATION_DATE DATE NOT NULL ENABLE,
    CREATED_BY VARCHAR2(200)  NOT NULL ENABLE,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY VARCHAR2(200)
)
$#$

CREATE TABLE CR_FBDI_TEMPLATE_COLS (
    FBDI_TEMPLATE_ID NUMBER NOT NULL ENABLE,
    FBDI_COLUMN_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1,
    FBDI_COLUMN_NAME VARCHAR2(100) NOT NULL ENABLE,
    COLUMN_SEQUENCE NUMBER,
    REQUIRED VARCHAR2(1),
    DATABASE_TABLE VARCHAR2(100),
    DATABASE_COLUMN VARCHAR2(100),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    CREATION_DATE DATE NOT NULL ENABLE,
    CREATED_BY VARCHAR2(200) NOT NULL ENABLE,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY VARCHAR2(200)
)
$#$

CREATE TABLE cr_object_group_hdrs (
    group_id         NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    project_id       NUMBER NOT NULL,
    parent_object_id NUMBER NOT NULL,
    group_name       VARCHAR2(250) NOT NULL,
    group_code       VARCHAR2(250) NOT NULL,
    description      VARCHAR2(400),
    attribute1       VARCHAR2(150),
    attribute2       VARCHAR2(150),
    attribute3       VARCHAR2(150),
    attribute4       VARCHAR2(150),
    attribute5       VARCHAR2(150),
    creation_date    DATE,
    created_by       VARCHAR2(200),
    last_update_date DATE,
    last_updated_by  VARCHAR2(200)
)
$#$

CREATE TABLE cr_object_group_lines (
    obj_grp_line_id  NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    group_id         NUMBER NOT NULL,
    object_id        NUMBER NOT NULL,
    sequence         NUMBER,
    attribute1       VARCHAR2(150),
    attribute2       VARCHAR2(150),
    attribute3       VARCHAR2(150),
    attribute4       VARCHAR2(150),
    attribute5       VARCHAR2(150),
    creation_date    DATE,
    created_by       VARCHAR2(200),
    last_update_date DATE,
    last_updated_by  VARCHAR2(200)
)
$#$

CREATE TABLE CR_PROCESS_REQUESTS (
    REQUEST_ID                    NUMBER          NOT NULL,
    REQUEST_TYPE                  VARCHAR2(50),
    CLD_TEMPLATE_ID               NUMBER ,
    SRC_TEMPLATE_ID               NUMBER,
    CR_BATCH_NAME                 VARCHAR2(2400),
    STATUS                        VARCHAR2(50),
    TOTAL_RECORDS                 NUMBER,
    COMPLETED_PERCENTAGE          NUMBER,
    START_DATE                    DATE,
    END_DATE                      DATE,
    ERR_MSG                       VARCHAR2(2000),
    USER_ID                       VARCHAR2(200),
    ATTRIBUTE1                    VARCHAR2(150),
    ATTRIBUTE2                    VARCHAR2(150),
    ATTRIBUTE3                    VARCHAR2(150),
    ATTRIBUTE4                    VARCHAR2(150),
    ATTRIBUTE5                    VARCHAR2(150),
    CREATION_DATE                 DATE            NOT NULL,
    CREATED_BY                    VARCHAR2(200)   NOT NULL,
    LAST_UPDATE_DATE              DATE,
    LAST_UPDATED_BY               VARCHAR2(200)
)
$#$

CREATE TABLE CR_PROCESS_JOBS (
    JOB_ID                    NUMBER         NOT NULL,
    JOB_NAME                  VARCHAR2(200),
    REQUEST_ID                NUMBER         NOT NULL,
    JOB_STATUS                VARCHAR2(50),
    WEIGHTAGE                 NUMBER,
    CR_BATCH_NAME             VARCHAR2(2400),
    SUCCESS_RECORDS           NUMBER,
    FAILURE_RECORDS           NUMBER,
    ERR_MSG                   VARCHAR2(2000),
    ATTRIBUTE1                VARCHAR2(150),
    ATTRIBUTE2                VARCHAR2(150),
    ATTRIBUTE3                VARCHAR2(150),
    ATTRIBUTE4                VARCHAR2(150),
    ATTRIBUTE5                VARCHAR2(150),
    CREATION_DATE             DATE            NOT NULL,
    CREATED_BY                VARCHAR2(200)   NOT NULL,
    LAST_UPDATE_DATE          DATE,
    LAST_UPDATED_BY           VARCHAR2(200)
)
$#$

CREATE TABLE CR_DATE_CONFIGURATION (
    ID                          NUMBER        NOT NULL,
    PROJECT_ID                  NUMBER        NOT NULL,
    PARENT_OBJECT_ID            NUMBER        NOT NULL,
    OBJECT_ID                   NUMBER        NOT NULL,
    SOURCE_DATE_FORMAT          VARCHAR2(200) NOT NULL,
    CLOUD_DATE_FORMAT           VARCHAR2(200) NOT NULL,
    ATTRIBUTE1                  VARCHAR2(150),
    ATTRIBUTE2                  VARCHAR2(150),
    ATTRIBUTE3                  VARCHAR2(150),
    ATTRIBUTE4                  VARCHAR2(150),
    ATTRIBUTE5                  VARCHAR2(150),
    CREATION_DATE               DATE,
    CREATED_BY                  VARCHAR2(200),
    LAST_UPDATE_DATE            DATE,
    LAST_UPDATED_BY             VARCHAR2(200)
)
$#$

CREATE TABLE CR_LOG_MESSAGES (
    Log_sequence           NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1 CACHE 20),
    PROC_NAME              VARCHAR2(150),
    REFERENCE_KEY          VARCHAR2(2000),
    Log_message            VARCHAR2(32767),
    DYNAMIC_QUERY          CLOB,
    USER_ID                VARCHAR2(200) ,
    AUDIT_WHEN             VARCHAR2(50),
    ATTRIBUTE1             VARCHAR2(150 BYTE),
    ATTRIBUTE2             VARCHAR2(150 BYTE),
    ATTRIBUTE3             VARCHAR2(150 BYTE),
    ATTRIBUTE4             VARCHAR2(150 BYTE),
    ATTRIBUTE5             VARCHAR2(150 BYTE),
    CREATION_DATE          DATE ,
    CREATED_BY             VARCHAR2(200) ,
    LAST_UPDATE_DATE       DATE,
    LAST_UPDATED_BY        VARCHAR2(200)
)
$#$
CREATE TABLE CR_SOURCE_LOAD_FAIL_RECORDS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    TEMPLATE_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(400),
    FAILED_RECORDS CLOB,
    LOG_FILE CLOB,
    CR_BATCH_NAME VARCHAR2(40),
    SUCCESS NUMBER,
    FAILED NUMBER,
    creation_date    DATE,
    created_by       VARCHAR2(200),
    last_update_date DATE,
    last_updated_by  VARCHAR2(200)
)
$#$

CREATE TABLE CR_CLOUD_JOB_STATUS (
JOB_ID                     NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1,
OBJECT_CODE                VARCHAR2(240),
OBJECT_ID                  NUMBER,
TYPE                       VARCHAR2(20),
CLD_TEMPLATE_ID            NUMBER,
DOCUMENT_AUTHOR            VARCHAR2(240),
DOCUMENT_TITLE             VARCHAR2(240),
DOCUMENT_SECURITY_GROUP    VARCHAR2(240),
DOCUMENT_ACCOUNT           VARCHAR2(240),
CONTENT_ID                 VARCHAR2(240),
LOAD_REQUEST_ID            NUMBER,
JOB_NAME                   VARCHAR2(240),
PARAMETER_LIST             VARCHAR2(240),
INTERFACE_ID               VARCHAR2(50 ),
JOB_STATUS                 VARCHAR2(240),
BATCH_NAME                 VARCHAR2(240),
ATTRIBUTE1                 VARCHAR2(240),
ATTRIBUTE2                 VARCHAR2(240),
ATTRIBUTE3                 VARCHAR2(240),
ATTRIBUTE4                 NUMBER,
ATTRIBUTE5                 NUMBER,
CREATION_DATE              DATE,
CREATED_BY                 VARCHAR2(200),
LAST_UPDATE_DATE           DATE,
LAST_UPDATED_BY            VARCHAR2(200)
)
$#$
CREATE TABLE CR_EBS_CONNECTION_DETAILS 
   (	CONNECT_ID NUMBER    GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 , 
   CONNECTION_NAME VARCHAR2(240),
	HOST_NAME VARCHAR2(240 ) , 
	PORT NUMBER, 
	SERVICE_NAME VARCHAR2(240) , 
	USER_NAME VARCHAR2(240 ) , 
	PASSWORD VARCHAR2(240 ) , 
	DATABASE_LINK VARCHAR2(240 ) , 
	ATTRIBUTE1 VARCHAR2(240 ) , 
	ATTRIBUTE2 VARCHAR2(240 ) , 
	ATTRIBUTE3 VARCHAR2(240 ) , 
	ATTRIBUTE4 VARCHAR2(240 ) , 
	ATTRIBUTE5 VARCHAR2(240 ) , 
	LAST_UPDATED_BY VARCHAR2(50 ) , 
	LAST_UPDATE_DATE DATE, 
	CREATION_DATE DATE, 
	CREATED_BY VARCHAR2(50 ) 
   )
$#$
CREATE TABLE CR_BATCH_PROCESS_DETAILS (
SRC_TEMP_ID NUMBER , 
OBJECT_ID NUMBER ,
SOURCE_COUNT NUMBER , 
 BATCH_NAME VARCHAR2(240),
NO_OF_BATCH_SPLIT  NUMBER ,
BATCH_NAME_POST_SPLIT CLOB ,
DUPLICATE_BATCH_NAME varchar2(240),
DUPLICATE_COUNT NUMBER , 
TOTAL_FUR_PROCESS_RECORDS NUMBER ,
ATTRIBUTE1 VARCHAR2(240),
ATTRIBUTE2 VARCHAR2(240),
ATTRIBUTE3 VARCHAR2(240),
ATTRIBUTE4 VARCHAR2(240),
ATTRIBUTE5 VARCHAR2(240),
CREATED_BY VARCHAR2(240),
CREATED_DATE DATE , 
UPDATED_BY VARCHAR2(240),
UPDATED_DATE DATE 
)
$#$

CREATE TABLE cr_objects (
    object_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_name VARCHAR2(150),
    object_code VARCHAR2(150),
    user_object_name VARCHAR2(150),
    module_code VARCHAR2(150),
    parent_object_id NUMBER,
    fbdi_sheet VARCHAR2(150),
    hdl_sheet VARCHAR2(150),
    loader_endpoint VARCHAR2(350),
    re_con_query CLOB,
    sequence_in_parent NUMBER,
    interface_table_name VARCHAR2(150),
    rejection_table_name VARCHAR2(150),
    ctl_file_name VARCHAR2(150),
    xlsm_file_name VARCHAR2(150),
    immediate_parent VARCHAR2(150),
    batch_size NUMBER,
    base_tables VARCHAR2(150),
     creation_date DATE NOT NULL,
    created_by VARCHAR2(150) NOT NULL,
    last_update_date DATE NOT NULL,
    last_update_by VARCHAR2(150) NOT NULL,
	ATTRIBUTE1 VARCHAR2(240),
    ATTRIBUTE2 VARCHAR2(240),
    ATTRIBUTE3 VARCHAR2(240),
    ATTRIBUTE4 VARCHAR2(240),
    ATTRIBUTE5 VARCHAR2(240),
    ATTRIBUTE6 VARCHAR2(240),
    ATTRIBUTE7 VARCHAR2(240),
    ATTRIBUTE8 VARCHAR2(240),
    ATTRIBUTE9 VARCHAR2(240),
    ATTRIBUTE10 VARCHAR2(240),
    ATTRIBUTE11 VARCHAR2(240),
    ATTRIBUTE12 VARCHAR2(240),
    ATTRIBUTE13 VARCHAR2(240),
    ATTRIBUTE14 VARCHAR2(240),
    ATTRIBUTE15 VARCHAR2(240),
    CONVERSION_TYPE VARCHAR2(50),
   	CLD_TEMPLATE_CODE VARCHAR2(50),
   	CLD_METADATA_TABLE_NAME VARCHAR2(50),
   	CLD_TEMPLATE_NAME VARCHAR2(50)
)
$#$
	
CREATE TABLE cr_object_information (
    obj_info_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id NUMBER NOT NULL,
    info_type VARCHAR2(250),
    info_value CLOB,
    info_description VARCHAR2(400),
    additional_information1 CLOB,
    additional_information2 CLOB,
    additional_information3 CLOB,
    additional_information4 CLOB,
    additional_information5 CLOB,
    creation_date DATE NOT NULL,
    created_by VARCHAR2(150) NOT NULL,
    last_update_date DATE NOT NULL,
    last_update_by VARCHAR2(150) NOT NULL,
	 ATTRIBUTE1 VARCHAR2(240),
    ATTRIBUTE2 VARCHAR2(240),
    ATTRIBUTE3 VARCHAR2(240),
    ATTRIBUTE4 VARCHAR2(240),
    ATTRIBUTE5 VARCHAR2(240),
    ATTRIBUTE6 VARCHAR2(240),
    ATTRIBUTE7 VARCHAR2(240),
    ATTRIBUTE8 VARCHAR2(240),
    ATTRIBUTE9 VARCHAR2(240),
    ATTRIBUTE10 VARCHAR2(240),
    ATTRIBUTE11 VARCHAR2(240),
    ATTRIBUTE12 VARCHAR2(240),
    ATTRIBUTE13 VARCHAR2(240),
    ATTRIBUTE14 VARCHAR2(240),
    ATTRIBUTE15 VARCHAR2(240),
    CONVERSION_TYPE VARCHAR2(255)
)
$#$

CREATE TABLE CR_TARGET_INTF_COLUMN_LIST (
    COLUMN_LIST_ID NUMBER  GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
    TARGET_SYSTEM VARCHAR2(1000),
    TARGET_SYSTEM_VERSION VARCHAR2(1000),
    OBJECT_ID NUMBER NOT NULL,
    COLUMN_NAME VARCHAR2(1000) NOT NULL,
    PHYSICAL_COLUMN_NAME VARCHAR2(1000) NOT NULL,
    USER_COLUMN_NAME VARCHAR2(1000) NOT NULL,
    COLUMN_DESCRPTION VARCHAR2(1000),
    COLUMN_SEQUENCE VARCHAR2(1000),
    COLUMN_TYPE VARCHAR2(1000),
    COLUMN_WIDTH VARCHAR2(1000),
    NULL_ALLOWED_FLAG VARCHAR2(1000),
    TRANSLATE_FLAG VARCHAR2(1),
    PRECISION VARCHAR2(1000),
    SCALE VARCHAR2(1000),
    DOMAIN_CODE VARCHAR2(1000),
    DENORM_PATH VARCHAR2(1000),
    ROUTING_MODE VARCHAR2(1000),
    CLOUD_VERSION VARCHAR2(1000),
    ELIGIBLE_TO_BE_SECURED VARCHAR2(1000),
    SECURITY_CLASSIFICATION VARCHAR2(1000),
    SEC_CLASSIFICATION_OVERRIDE VARCHAR2(1000),
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    CREATION_DATE DATE NOT NULL,
    CREATED_BY VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY VARCHAR2(200)
)
$#$