DECLARE
    l_config_task_code_count          NUMBER;
    l_project_type_count              NUMBER;
    l_cr_custom_tables                NUMBER;
    l_cr_custom_columns               NUMBER;
    l_cr_custom_source_table_dtls     NUMBER;
    l_cr_custom_loaddata_fail_records NUMBER;
    l_CR_TRANSFORM_STATS		number;
    L_JOB_ERROR_MESSAGE_COUNT NUMBER ;
    L_ADDITIONAL_INFO_COUNT NUMBER ;
L_CLOUD_LOG_DETAILS_COUNT NUMBER ;
L_BANK_ACCOUNT_ERROR_COUNT NUMBER ;

L_CLD_REC_COUNT NUMBER ;
l_cr_async_process_records NUMBER ;
BEGIN
    -- Check if the table exists
    SELECT
        COUNT(*)
    INTO l_config_task_code_count
    FROM
        all_tables
    WHERE
        table_name = 'CR_CONFIG_TASK_CODE_DETAILS';

    IF l_config_task_code_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CR_CONFIG_TASK_CODE_DETAILS (
                CONFIG_ID NUMBER GENERATED ALWAYS AS IDENTITY 
                          MINVALUE 1 
                          MAXVALUE 9999999999999999999999999999 
                          INCREMENT BY 1 
                          START WITH 1 
                          NOT NULL, 
                TASK_CODE VARCHAR2(255), 
                METADATA_BLOB BLOB, 
                DATA BLOB,
                ATTRIBUTE1 VARCHAR2(240),
                ATTRIBUTE2 VARCHAR2(240),
                ATTRIBUTE3 VARCHAR2(240),
                ATTRIBUTE4 VARCHAR2(240),
                ATTRIBUTE5 VARCHAR2(240),
                CREATION_DATE DATE NOT NULL,
                CREATED_BY VARCHAR2(150) NOT NULL,
                LAST_UPDATE_DATE DATE NOT NULL,
                LAST_UPDATE_BY VARCHAR2(150) NOT NULL
            )';
    END IF;
    BEGIN
        SELECT
            COUNT(*)
        INTO l_project_type_count
        FROM
            all_tab_columns
        WHERE
                table_name = 'CR_PROJECT_OBJECTS'
            AND column_name = 'CONVERSION_TYPE';

        IF l_project_type_count = 0 THEN
            EXECUTE IMMEDIATE ' ALTER TABLE CR_PROJECT_OBJECTS ADD CONVERSION_TYPE VARCHAR2(240)';
        END IF;
    END;

    BEGIN
        SELECT
            COUNT(*)
        INTO l_cr_custom_tables
        FROM
            all_tables
        WHERE
            table_name = 'CR_CUSTOM_TABLES';

        IF l_cr_custom_tables = 0 THEN
            EXECUTE IMMEDIATE '
           CREATE TABLE CR_CUSTOM_TABLES (
    TABLE_ID                      NUMBER  GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1,
    TABLE_NAME                    VARCHAR2(100)  NOT NULL UNIQUE,
    USER_TABLE_NAME               VARCHAR2(80)   NOT NULL,
    DESCRIPTION                   VARCHAR2(240) ,
    OBJECT_ID                     NUMBER,
    APPLICATION_ID                NUMBER(15)  NOT NULL ,
    AUTO_SIZE                     VARCHAR2(1)  NOT NULL,
    TABLE_TYPE                    VARCHAR2(1) NOT NULL ,
    INITIAL_EXTENT                NUMBER(15)  NOT NULL ,
    NEXT_EXTENT                   NUMBER(15)  NOT NULL,
    MIN_EXTENTS                   NUMBER(15)  NOT NULL ,
    MAX_EXTENTS                   NUMBER(15)  NOT NULL ,
    PCT_INCREASE                  NUMBER(15)  NOT NULL ,
    INI_TRANS                     NUMBER(15)  NOT NULL ,
    MAX_TRANS                     NUMBER(15)  NOT NULL ,
    PCT_FREE                      NUMBER(15)  NOT NULL ,
    PCT_USED                      NUMBER(15)  NOT NULL ,
    HOSTED_SUPPORT_STYLE          VARCHAR2(30),
    IREP_COMMENTS                 VARCHAR2(4000),
    IREP_ANNOTATIONS              VARCHAR2(4000),
    ATTRIBUTE1                    VARCHAR2(150),
    ATTRIBUTE2                    VARCHAR2(150),
    ATTRIBUTE3                    VARCHAR2(150),
    ATTRIBUTE4                    VARCHAR2(150),
    ATTRIBUTE5                    VARCHAR2(150),
    CREATION_DATE                 DATE NOT NULL,
    CREATED_BY                    VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE              DATE,
    LAST_UPDATED_BY               VARCHAR2(200)
)';
        END IF;
    END;

    BEGIN
        SELECT
            COUNT(*)
        INTO l_cr_custom_columns
        FROM
            all_tables
        WHERE
            table_name = 'CR_CUSTOM_COLUMNS';

        IF l_cr_custom_columns = 0 THEN
            EXECUTE IMMEDIATE '
           CREATE TABLE CR_CUSTOM_COLUMNS (
    TABLE_ID                         NUMBER(15)       NOT NULL,
    COLUMN_ID                        NUMBER(15)       NOT NULL,
    COLUMN_NAME                      VARCHAR2(240)    NOT NULL,
    USER_COLUMN_NAME                 VARCHAR2(240)    NOT NULL,
    DESCRIPTION                      VARCHAR2(240),
    APPLICATION_ID                   NUMBER(15)       NOT NULL,
    COLUMN_SEQUENCE                  NUMBER(15)       NOT NULL,
    COLUMN_TYPE                      VARCHAR2(1)      NOT NULL,
    WIDTH                            NUMBER(15),
    NULL_ALLOWED_FLAG                VARCHAR2(1)      NOT NULL,
    TRANSLATE_FLAG                   VARCHAR2(1)      NOT NULL,
    FLEXFIELD_USAGE_CODE             VARCHAR2(1)      NOT NULL,
    FLEXFIELD_APPLICATION_ID         NUMBER(10),
    FLEXFIELD_NAME                   VARCHAR2(30),
    FLEX_VALUE_SET_APPLICATION_ID    NUMBER(10),
    FLEX_VALUE_SET_ID                NUMBER(10),
    DEFAULT_VALUE                    VARCHAR2(2000),
    PRECISION                        NUMBER(15),
    SCALE                            NUMBER(15),
    IREP_COMMENTS                    VARCHAR2(4000),
    ATTRIBUTE1                       VARCHAR2(150),
    ATTRIBUTE2                       VARCHAR2(150),
    ATTRIBUTE3                       VARCHAR2(150),
    ATTRIBUTE4                       VARCHAR2(150),
    ATTRIBUTE5                       VARCHAR2(150),
    CREATION_DATE                    DATE NOT NULL,
    CREATED_BY                       VARCHAR2(200) NOT NULL,
    LAST_UPDATE_DATE                 DATE,
    LAST_UPDATED_BY                  VARCHAR2(200),
    CONSTRAINT CUSTOM_COL_UNIQUE UNIQUE (TABLE_ID, COLUMN_NAME)
)';
        END IF;
    END;

    BEGIN
        SELECT
            COUNT(*)
        INTO l_cr_custom_source_table_dtls
        FROM
            all_tables
        WHERE
            table_name = 'CR_CUSTOM_SOURCE_TABLE_DTLS';

        IF l_cr_custom_source_table_dtls = 0 THEN
            EXECUTE IMMEDIATE '
           CREATE TABLE CR_CUSTOM_SOURCE_TABLE_DTLS(
   CUSTOM_TABLE_ID           NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1,
   PROJECT_ID                NUMBER,
   PARENT_OBJECT_ID          NUMBER,
   OBJECT_ID                 NUMBER,
   METADATA_TABLE_ID         NUMBER,
   CUSTOM_TABLE_NAME         VARCHAR2(50) NOT NULL UNIQUE,
   ATTRIBUTE1                       VARCHAR2(150),
   ATTRIBUTE2                       VARCHAR2(150),
   ATTRIBUTE3                       VARCHAR2(150),
   ATTRIBUTE4                       VARCHAR2(150),
   ATTRIBUTE5                       VARCHAR2(150),
   CREATION_DATE                    DATE NOT NULL,
   CREATED_BY                       VARCHAR2(200) NOT NULL,
   LAST_UPDATE_DATE                 DATE,
   LAST_UPDATED_BY                  VARCHAR2(200)
)';
        END IF;
    END;

    BEGIN
        SELECT
            COUNT(*)
        INTO l_cr_custom_loaddata_fail_records
        FROM
            all_tables
        WHERE
            table_name = 'CR_CUSTOM_LOADDATA_FAIL_RECORDS';

        IF l_cr_custom_loaddata_fail_records = 0 THEN
            EXECUTE IMMEDIATE '
           CREATE TABLE CR_CUSTOM_LOADDATA_FAIL_RECORDS
   ( RECORD_ID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1, 
	CUSTOM_TABLE_ID NUMBER, 
	FILE_NAME VARCHAR2(300), 
	LOG_FILE_BLOB CLOB, 
	CR_BATCH_NAME VARCHAR2(240), 
	FAILED_CLOB CLOB, 
	SUCCESS_COUNT NUMBER, 
	FAILED_COUNT NUMBER, 
	ATTRIBUTE1 VARCHAR2(150), 
	ATTRIBUTE2 VARCHAR2(150), 
	ATTRIBUTE3 VARCHAR2(150), 
	ATTRIBUTE4 VARCHAR2(150), 
	ATTRIBUTE5 VARCHAR2(150), 
	CREATION_DATE DATE NOT NULL , 
	CREATED_BY VARCHAR2(200) NOT NULL , 
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(200)
   )';
        END IF;
    END;
Begin
	SELECT
        COUNT(1)
    INTO l_CR_TRANSFORM_STATS
    FROM
        all_tables
    WHERE
        table_name = 'CR_TRANSFORM_STATS';

    IF l_CR_TRANSFORM_STATS = 0 THEN
        EXECUTE IMMEDIATE Q'[
	CREATE TABLE CR_TRANSFORM_STATS (
	CLOUD_TEMPLATE_ID NUMBER, 
	CLOUD_TEMPLATE_NAME VARCHAR2(250), 
	PROJECT_ID NUMBER, 
	PROJECT VARCHAR2(250), 
	PARENT_OBJECT_ID NUMBER, 
	PARENT_OBJECT_CODE VARCHAR2(250), 
	OBJECT_ID NUMBER, 
	OBJECT VARCHAR2(250), 
	SRC_STG_TABLE_NAME VARCHAR2(250), 
	CLD_STG_TABLE_NAME VARCHAR2(250), 
	TOTAL_SOURCE_RECORDS NUMBER, 
	TOTAL_CLOUD_RECORDS NUMBER, 
	VALIDATION_FAILED VARCHAR2(250), 
	VALIDATION_PASSED VARCHAR2(250), 
	SOURCE_UNVERFIED VARCHAR2(250), 
	VS_TRANS_REC NUMBER, 
	VS_UNTRANS_REC NUMBER, 
	VF_TRANS_REC NUMBER, 
	VF_UNTRANS_REC NUMBER, 
	CLOUD_UNKOWN_RECORDS NUMBER, 
	TOTAL_UNTRANS_REC NUMBER, 
	CLOUD_INT_REJ_REC NUMBER, 
	CLOUD_SUCCESS_REC NUMBER, 
	CR_BATCH_NAME VARCHAR2(250), 
	LOAD_REQUEST_ID NUMBER, 
	LATEST_FLAG VARCHAR2(10),
	COMMENTS VARCHAR2(2000),
	ATTRIBUTE1 VARCHAR2(250), 
	ATTRIBUTE2 VARCHAR2(250), 
	ATTRIBUTE3 VARCHAR2(250), 
	ATTRIBUTE4 VARCHAR2(250), 
	ATTRIBUTE5 VARCHAR2(250), 
	CREATED_BY VARCHAR2(250), 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(250), 
	LAST_UPDATED_DATE DATE
   )]';
	end if;
end;


 BEGIN
        SELECT
            COUNT(*)
        INTO L_JOB_ERROR_MESSAGE_COUNT
        FROM
            all_tab_columns
        WHERE
                table_name = 'CR_CLOUD_JOB_STATUS'
            AND column_name = 'JOB_ERROR_MESSAGE';

        IF L_JOB_ERROR_MESSAGE_COUNT = 0 THEN
            EXECUTE IMMEDIATE ' ALTER TABLE CR_CLOUD_JOB_STATUS  ADD  JOB_ERROR_MESSAGE VARCHAR2(240)';
        END IF;
    END;
    
    BEGIN
        SELECT
            COUNT(*)
        INTO L_ADDITIONAL_INFO_COUNT
        FROM
            all_tab_columns
        WHERE
                table_name = 'CR_CLOUD_JOB_STATUS'
            AND column_name = 'ADDITIONAL_INFO';

        IF L_ADDITIONAL_INFO_COUNT = 0 THEN
            EXECUTE IMMEDIATE ' ALTER TABLE CR_CLOUD_JOB_STATUS  ADD  ADDITIONAL_INFO VARCHAR2(420)';
        END IF;
    END;
BEGIN
    -- Check if the table exists
    SELECT
        COUNT(*)
    INTO L_CLOUD_LOG_DETAILS_COUNT
    FROM
        all_tables
    WHERE
        table_name = 'CR_CLOUD_LOG_DETAILS';

    IF L_CLOUD_LOG_DETAILS_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CR_CLOUD_LOG_DETAILS 
( 
LOG_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY  , 
LOAD_REQUEST_ID NUMBER UNIQUE  , 
LOG_FILE BLOB ,
ATTRIBUTE1 VARCHAR2(240),
ATTRIBUTE2 VARCHAR2(240),
ATTRIBUTE3 VARCHAR2(240),
ATTRIBUTE4 VARCHAR2(240),
ATTRIBUTE5 NUMBER ,
ATTRIBUTE6 NUMBER,
ATTRIBUTE7 NUMBER,
ATTRIBUTE8 NUMBER,
CREATED_BY VARCHAR2(240),
CREATION_DATE DATE,
LAST_UPDATED_BY VARCHAR2(240),
LAST_UPDATE_DATE DATE
)';
    END IF;
END ;

BEGIN
  SELECT
        COUNT(*)
    INTO L_BANK_ACCOUNT_ERROR_COUNT
    FROM
        all_tables
    WHERE
        table_name = 'CR_CREATE_BANK_ACCOUNT_ERRORS';
	dbms_output.put_line('The count of  table L_BANK_ACCOUNT_ERROR_COUNT  :'||L_BANK_ACCOUNT_ERROR_COUNT);
    IF L_BANK_ACCOUNT_ERROR_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CR_CREATE_BANK_ACCOUNT_ERRORS (
    ID  NUMBER  GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1,
    ACCOUNT_HOLDER_NAME VARCHAR2(255),
    ACCOUNT_HOLDER_NAME_ALT VARCHAR2(255),
    ACCOUNTING_CONVERSION_RATE_TYPE VARCHAR2(255),
    ACCOUNT_SUFFIX VARCHAR2(255),
    ACCOUNT_TYPE VARCHAR2(255),
    AGENCY_LOCATION_CODE VARCHAR2(255),
    AP_USE_ALLOWED_FLAG VARCHAR2(255),
    AR_USE_ALLOWED_FLAG VARCHAR2(255),
    BANK_ACCOUNT_ID VARCHAR2(255),
    BANK_ACCOUNT_NAME VARCHAR2(255),
    BANK_ACCOUNT_NAME_ALT VARCHAR2(255),
    BANK_ACCOUNT_NUMBER VARCHAR2(255),
    BANK_ACCOUNT_NUMBER_ELECTRONIC VARCHAR2(255),
    BANK_BRANCH_NAME VARCHAR2(255),
    BANK_EXCHANGE_RATE_TYPE VARCHAR2(255),
    BANK_NAME VARCHAR2(255),
    BRANCH_NUMBER VARCHAR2(255),
    CASH_ACCOUNT_COMBINATION VARCHAR2(255),
    CASH_CCID_FIXED_SEGMENTS VARCHAR2(255),
    CASH_CLEARING_ACCOUNT_COMBINATION VARCHAR2(255),
    CHECK_DIGITS VARCHAR2(255),
    COUNTRY_NAME VARCHAR2(255),
    CURRENCY_CODE VARCHAR2(255),
    DATA_SECURITY_FLAG VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    EFT_USER_NUMBER VARCHAR2(255),
    END_DATE DATE,
    GL_RECON_START_DATE DATE,
    IBAN_NUMBER VARCHAR2(255),
    LEGAL_ENTITY_NAME VARCHAR2(255),
    MASKED_ACCOUNT_NUMBER VARCHAR2(255),
    MASKED_IBAN VARCHAR2(255),
    MAXIMUM_CHECK_AMOUNT VARCHAR2(255),
    MAXIMUM_OUTLAY VARCHAR2(255),
    MINIMUM_CHECK_AMOUNT VARCHAR2(255),
    MULTI_CASH_RECON_ENABLED_FLAG VARCHAR2(255),
    MULTI_CURRENCY_ALLOWED_FLAG VARCHAR2(255),
    NETTING_ACCOUNT_FLAG VARCHAR2(255),
    PARSING_RULE_SET_NAME VARCHAR2(255),
    PAY_USE_ALLOWED_FLAG VARCHAR2(255),
    POOLED_FLAG VARCHAR2(255),
    RECONCILIATION_DIFFERENCE_ACCOUNT_COMBINATION VARCHAR2(255),
    RECON_START_DATE DATE,
    REVERSAL_PROCESSING_METHOD VARCHAR2(255),
    RULESET_NAME VARCHAR2(255),
    SECONDARY_ACCOUNT_REFERENCE VARCHAR2(255),
    TARGET_BALANCE VARCHAR2(255),
    TOLERANCE_RULE_NAME VARCHAR2(255),
    TRANSACTION_CALENDAR VARCHAR2(255),
    ZERO_AMOUNT_ALLOWED VARCHAR2(255),
    ERROR_TYPE VARCHAR2(255),
    CR_BATCH_NAME VARCHAR2(255),
    ERROR_MESSAGE VARCHAR2(4000),
    CREATION_DATE DATE,
    CREATED_BY VARCHAR2(255),
    PRIMARY KEY (ID)

            )';
	ELSE 
	
	dbms_output.put_line('The count of table L_BANK_ACCOUNT_ERROR_COUNT  :'||L_BANK_ACCOUNT_ERROR_COUNT);
	dbms_output.put_line('The  table going to dropped CR_CREATE_BANK_ACCOUNT_ERRORS ');
	EXECUTE IMMEDIATE 'DROP TABLE CR_CREATE_BANK_ACCOUNT_ERRORS';
	
	dbms_output.put_line('The table got dropped and we will recreate the table CR_CREATE_BANK_ACCOUNT_ERRORS ');
	
	EXECUTE IMMEDIATE '
            CREATE TABLE CR_CREATE_BANK_ACCOUNT_ERRORS (
    ID NUMBER   GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1,
    ACCOUNT_HOLDER_NAME VARCHAR2(255),
    ACCOUNT_HOLDER_NAME_ALT VARCHAR2(255),
    ACCOUNTING_CONVERSION_RATE_TYPE VARCHAR2(255),
    ACCOUNT_SUFFIX VARCHAR2(255),
    ACCOUNT_TYPE VARCHAR2(255),
    AGENCY_LOCATION_CODE VARCHAR2(255),
    AP_USE_ALLOWED_FLAG VARCHAR2(255),
    AR_USE_ALLOWED_FLAG VARCHAR2(255),
    BANK_ACCOUNT_ID VARCHAR2(255),
    BANK_ACCOUNT_NAME VARCHAR2(255),
    BANK_ACCOUNT_NAME_ALT VARCHAR2(255),
    BANK_ACCOUNT_NUMBER VARCHAR2(255),
    BANK_ACCOUNT_NUMBER_ELECTRONIC VARCHAR2(255),
    BANK_BRANCH_NAME VARCHAR2(255),
    BANK_EXCHANGE_RATE_TYPE VARCHAR2(255),
    BANK_NAME VARCHAR2(255),
    BRANCH_NUMBER VARCHAR2(255),
    CASH_ACCOUNT_COMBINATION VARCHAR2(255),
    CASH_CCID_FIXED_SEGMENTS VARCHAR2(255),
    CASH_CLEARING_ACCOUNT_COMBINATION VARCHAR2(255),
    CHECK_DIGITS VARCHAR2(255),
    COUNTRY_NAME VARCHAR2(255),
    CURRENCY_CODE VARCHAR2(255),
    DATA_SECURITY_FLAG VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    EFT_USER_NUMBER VARCHAR2(255),
    END_DATE DATE,
    GL_RECON_START_DATE DATE,
    IBAN_NUMBER VARCHAR2(255),
    LEGAL_ENTITY_NAME VARCHAR2(255),
    MASKED_ACCOUNT_NUMBER VARCHAR2(255),
    MASKED_IBAN VARCHAR2(255),
    MAXIMUM_CHECK_AMOUNT VARCHAR2(255),
    MAXIMUM_OUTLAY VARCHAR2(255),
    MINIMUM_CHECK_AMOUNT VARCHAR2(255),
    MULTI_CASH_RECON_ENABLED_FLAG VARCHAR2(255),
    MULTI_CURRENCY_ALLOWED_FLAG VARCHAR2(255),
    NETTING_ACCOUNT_FLAG VARCHAR2(255),
    PARSING_RULE_SET_NAME VARCHAR2(255),
    PAY_USE_ALLOWED_FLAG VARCHAR2(255),
    POOLED_FLAG VARCHAR2(255),
    RECONCILIATION_DIFFERENCE_ACCOUNT_COMBINATION VARCHAR2(255),
    RECON_START_DATE DATE,
    REVERSAL_PROCESSING_METHOD VARCHAR2(255),
    RULESET_NAME VARCHAR2(255),
    SECONDARY_ACCOUNT_REFERENCE VARCHAR2(255),
    TARGET_BALANCE VARCHAR2(255),
    TOLERANCE_RULE_NAME VARCHAR2(255),
    TRANSACTION_CALENDAR VARCHAR2(255),
    ZERO_AMOUNT_ALLOWED VARCHAR2(255),
    ERROR_TYPE VARCHAR2(255),
    CR_BATCH_NAME VARCHAR2(255),
    ERROR_MESSAGE VARCHAR2(4000),
    CREATION_DATE DATE,
    CREATED_BY VARCHAR2(255),
    PRIMARY KEY (ID)

            )';

	
    END IF;
END ;

BEGIN
        SELECT
            COUNT(*)
        INTO L_CLD_REC_COUNT
        FROM
            all_tab_columns
        WHERE
                table_name = 'CR_PROCESS_REQUESTS'
            AND column_name = 'CLD_RECORD_COUNT';

        IF L_CLD_REC_COUNT = 0 THEN
            EXECUTE IMMEDIATE ' ALTER TABLE CR_PROCESS_REQUESTS ADD CLD_RECORD_COUNT NUMBER';
        END IF;
    END;


BEGIN
    SELECT
        COUNT(*)
    INTO l_cr_async_process_records
    FROM
        all_tables
    WHERE
        table_name = 'CR_ASYNC_PROCESS_STATUS';

    IF l_cr_async_process_records = 0 THEN
        EXECUTE IMMEDIATE '
           CREATE TABLE CR_ASYNC_PROCESS_STATUS
   (	ASYNC_PROCESS_ID NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	ASYNC_PROCESS_NAME VARCHAR2(255 ) , 
	ASYNC_START_TIME TIMESTAMP (6), 
	ASYNC_END_TIME TIMESTAMP (6), 
	ASYNC_PROCESS_STATUS VARCHAR2(50) , 
	ERROR_MESSAGE VARCHAR2(4000) , 
	CREATED_BY VARCHAR2(50) , 
	CREATED_DATE TIMESTAMP (6) , 
	LAST_UPDATED_BY VARCHAR2(50) , 
	LAST_UPDATED_DATE TIMESTAMP (6)
   )';
    END IF;
END;
END;

$#$
